spring.application.name=train-gateway
server.port=8000
module.name=Gateway

spring.cloud.gateway.route[0].id=member
spring.cloud.gateway.route[0].uri=http://127.0.0.1:8001
spring.cloud.gateway.route[0].predicates[0]=Path=/member/**